# Generated by Django 5.1.3 on 2024-11-14 17:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nasc', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('pcd', models.CharField(blank=True, max_length=50, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=255, null=True)),
                ('has_preferred_name', models.BooleanField(blank=True, null=True)),
                ('cel', models.CharField(blank=True, max_length=15, null=True)),
                ('cel_responsavel', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=50, null=True)),
                ('raca', models.CharField(blank=True, max_length=10, null=True)),
                ('renda_familiar', models.CharField(blank=True, max_length=50, null=True)),
                ('cadastro_completo', models.BooleanField(blank=True, null=True)),
                ('registration_status', models.CharField(choices=[('aprovado', 'Aprovado'), ('em_andamento', 'Em Andamento'), ('matriculado', 'Matriculado'), ('reprovado', 'Reprovado'), ('espera', 'Espera')], default='espera', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('rua', models.CharField(blank=True, max_length=255, null=True)),
                ('bairro', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.CharField(blank=True, max_length=10, null=True)),
                ('complemento', models.CharField(blank=True, max_length=255, null=True)),
                ('city_id', models.UUIDField(blank=True, null=True)),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='api.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_method', models.CharField(blank=True, max_length=50, null=True)),
                ('apply_method_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('test_id', models.UUIDField(blank=True, null=True)),
                ('school_year', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('absent', models.BooleanField(blank=True, null=True)),
                ('enrolled', models.BooleanField(blank=True, null=True)),
                ('disqualified', models.BooleanField(blank=True, null=True)),
                ('practice_test_id', models.UUIDField(blank=True, null=True)),
                ('school_award', models.CharField(blank=True, max_length=255, null=True)),
                ('nota_matematica', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_redacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nota_geral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('media_ensino_medio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('pdf_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_data', to='api.userprofile')),
            ],
        ),
    ]
