# Generated by Django 5.1.3 on 2024-11-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicdata',
            name='contract_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
